language: c
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      env:
	   - DISTRO="trusty"
	   - TEST=BASIC
    - os: linux
      dist: trusty
      env:
	   - DISTRO="trusty"
	   - TEST=INSTALLATION
    - os: linux
      dist: precise
      env:
	   - DISTRO="precise"
	   - TEST=BASIC
    - os: linux
      dist: precise
      env:
 	   - DISTRO="precise"
 	   - TEST=INSTALLATION
    - os: osx
      env:
 	   - DISTRO="precise"
 	   - TEST=BASIC
    - os: osx
      env:
 	   - DISTRO="precise"
 	   - TEST=INSTALLATION

before_install:
    - echo "BEFORE INSTALL" 
    - if [[ "$DISTRO" == "trusty" ]]; then sudo dpkg --add-architecture i386        ; fi 
    - if [[ "$DISTRO" == "trusty" ]]; then sudo apt-get update ; fi
    - sudo apt-get install libssl1.0.0:i386 libfreetype6:i386 libasound2:i386 lib32z1 lib32bz2-1.0


install: 
  - if [[ "$TEST" == "BASIC" ]]; then sudo ./setupScaleDev.sh ; fi 
script:
 - if [[ "$TEST" == "INSTALLATION" ]]; then ./build/build.sh ; fi
 - if [[ "$TEST" == "INSTALLATION" ]]; then sudo ./build/scale-bootstrap build/install.st ; fi
 - if [[ "$TEST" == "INSTALLATION" ]]; then sudo ./build/scale-bootstrap build/uninstall.st ; fi
 - if [[ "$TEST" == "BASIC" ]]; then ./examples/lsst.st ; fi
 - if [[ "$TEST" == "BASIC" ]]; then ./examples/ls.st ; fi
 - if [[ "$TEST" == "BASIC" ]]; then ./examples/fact.st ; fi
 - if [[ "$TEST" == "BASIC" ]]; then ./examples/download.st -v 60 ; fi
 - if [[ "$TEST" == "BASIC" ]]; then ./examples/parallel-call.st ; fi
 - if [[ "$TEST" == "BASIC" ]]; then ./examples/parallel-call2.st ; fi
 - if [[ "$TEST" == "BASIC" ]]; then ./examples/stdout.st ; fi




























 
