language: c
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      env: DISTRO="trusty"
    - os: linux
      dist: precise
      env: DISTRO="precise"
    - os: osx
      env: DISTRO="osx"

before_install:
    - echo "BEFORE INSTALL" 
    - if [[ "$DISTRO" == "trusty" ]]; then sudo dpkg --add-architecture i386        ; fi 
    - if [[ "$DISTRO" == "trusty" ]]; then sudo apt-get update ; fi

addons:
  apt:
    packages:
      - lib32asound2
      - lib32z1
      - lib32bz2-1.0
      - libssl1.0.0:i386
      - libfreetype6:i386

install: 
  - sudo ./setupScaleDev.sh
script:
 - ./examples/lsst.st
 - ./examples/ls.st
 - ./examples/fact.st
 - ./examples/download.st -v 60
 - ./examples/parallel-call.st
 - ./examples/parallel-call2.st
 - ./examples/stdout.st




























 
